### ISSUE TITLE
Borrar jony1.html

### ISSUE THREAD

**Issue by Beagampad** [mikeloguay/bootcamp2-row2#2]
Para que no quede basurilla @Jbraxs

**Comment by Jbraxs** [comment]
@Beagampad gracias por la tarea. Recuerda por favor encargarte de: 
-ejercicios de javi
- volver a diseñar las bicis. 

gracias

**Comment by Gabrielasosa** [comment]
hola creo que no es apropiado el lenguaje que utilizáis, voy a reportaros. muchas gracias
